services:
  mongo:
    image: mongo
    ports:
     - 3456:27017

  server:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
